### ISSUE TITLE
Snoopy and Hobbes have turned on their owners

### ISSUE THREAD

**Issue by paulsbduncan** [blairconrad/notions#2]
Or maybe not? I'm not sure, because all I see lately is:

Couldn't find comic for peanuts
Couldn't find comic for calvinandhobbes

**Comment by blairconrad** [comment]
To be fair, at least one of the owners was asking for it.

**Comment by blairconrad** [comment]
Thanks for bringing this up, @paulsbduncan. Things should be fixed now. I've sent you a bonus edition.

**Comment by paulsbduncan** [comment]
I see the new comic! Thank you so much!
